### ISSUE TITLE
Question: how does this relate to zmq?

### ISSUE THREAD

**Issue by Totodebrant** [threefoldtech/zbus#23]
So 3 small questions to try and wrap my head around all the components of zos:
- How does zbus relate to something like zmq (https://zeromq.org/get-started/)?
- What was the motivation to build zbus (and rbus), instead of working with redis or zmq directly?
- By using redis there is a dependency on the server being online for the clients to communicate, I suppose this is somehow mitigated on failure, where can I find more on this in the code?

**Comment by muhamadazmy** [comment]
- ZMQ is an over kill for a `local` message bus. redis is used by other components on the system so it was easier and more efficient to leverage on it instead of installing yet another server
- ZBUS is a set of libraries that abstracts the usage of redis queues to implement RPC. So servers (and clients) do not need to deal with queuing, dequeuing, packing of requests and response, etc.. on their own. The FULL idea behind zbus is that we:
- Define the service interface with simple go interfaces. Then a server can implement this interface then run it.
- Using the same interfaces we can simply generate a client stub (so client doesn't have to know about which queues, or how the data is packed) then it can use the client normally to do RPC.
  - Please check the example folder on how it's used.

So now, zos has many modules each run as a separate service, sometimes they need to communicate so what happens is each module exposes a zbus service (if it provide a LOCAL api).

If service A needs to call a function that is provided by service B all what it needs to do is create an instance of the service B stub, and make the call.

Again, zbus is designed only for local RPC it should not be used across multiple servers (although you can) because it assumes full trust of the server/client. It was done like this because it was built with only ZOS modules in mind

**Comment by Totodebrant** [comment]
Thank you for the detailed explanation, this made the decisions more clear. Also looked further at the examples and it starts to make sense!
